---
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-kafka-secret"
  namespace: "dev-env"
  labels:
    app.kubernetes.io/name: "datahub-kafka-secret"
    app.kubernetes.io/version: "0.0.1"
type: Opaque
data:
  keystore.p12: "{{ .Values.kafkaSSLKeystoreBase64 }}"
  truststore.jks: "{{ .Values.kafkaSSLTruststoreBase64 }}"
stringData:
  KAFKA_SSL_KEYSTORE_PASSWORD: "{{ .Values.kafkaSSLKeystorePassword }}"
  KAFKA_SSL_TRUSTSTORE_PASSWORD: "{{ .Values.kafkaSSLTruststorePassword }}"