---
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-kafka-secrets"
  namespace: "test-env"
  labels:
    app.kubernetes.io/name: "datahub-kafka-secrets"
    app.kubernetes.io/version: "0.0.1"
type: Opaque
data:
  keystore.p12: |
    MIINDAIBAzCCDNIGCSqGSIb3DQEHAaCCDMMEggy/MIIMuzCCBQ8GCSqGSIb3DQEHBqCCBQAwggT8
    AgEAMIIE9QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI9EjBW+i7SvYCAggAgIIEyAwMVTWC
    YlOdlDwcXkLn8HNE1S36xXc12rorvtiAeBXbVWVxqhNjp7m9xzMpmhrkBlHn/BYc3Qf+lSfi2f90
    vKrxKRiN7BNh1zOwabdNAtTueEQomlluz81YnRxSBk9Dg20otSiz0UjQLMfEW8pylidAdarXlcgA
    /JsQvuFy5AKLx8CAeroeNwjkuHQ3+giSdrm6JKp6nNLZg2yWmX9MkncNrjXErI3r38pyMYmhVOZ3
    IdOoEvfICLFmnIG4NUPVBiXfW3BQWXE1LX4pcCjkN+EQvc9u2nU3/vugRz2f4LQyrTafVDO+yD4O
    kHLUiZh2a7REl+ZjXyGl5P7T+zfr2ZfjHtQs67/oms4ijJZzBm9vkaAe758v4rydXzKMyqQp128Z
    2vJSp+sRhnOBrocp1VQXeoUxGRZcuJpyi2ni9BZLvKPt/iFnWOnv/umSmSDnrkImOv/eFDCuAsPL
    Cfxnk5//boNN/EwOko+QXQMon8I/yQ58oRQ7XoXXMPORlhP6Hcz4fzBSC36dAdropO9BVlObzcEk
    lkLSLL4KBxbFyG1kvrlF0uVhYotcQ5Hm3aXgq5arTStGzHNd6v0dUARZqZjsB935YKvqny/lgJZm
    N2zmIzBjh9CLQUBoIjRsPnq3SEMdLXgbd/K4hPGwAyJNM1vimzSLsbVnKvAuZ5HNXBubY80tzyp8
    w0FdTejooR79F1dKf9MGTCr/lHfDx4hxkLQLslAoCS7qSTSzM5D63YlyJZCMIAXEF8/jAwiAZMkp
    WIGukFXte1t4lR4nHnaX+YfmDgDJC3KSLTVQRmY6r0CoDaOQzIm+AWu51Er5UCFHWF4M325xrcd2
    mFWbipCRxxFrjisca0aRv9rEMB7POsdnST6lLFtdJu3KqGvdGktAc6dFD5+0hqGfFpCCE3kkVLAF
    MjjQAxbZouoBQH5P2G0iHL90m6TV2EAYMvR59rJ5B593B0fFqxE1+x+WFQFiBfamJoNG6JUfiIkG
    wl5QvnYtHcdp3Nn17DjnP7mWLUGO8Rqyp+o27bz5/46Zw9RtgiscmUFEPO0pswBtCByvZ5b3c30Z
    +RB9OY2VzoV8l4O6qMAJ19V/hMkzHA9lYOlPAY7r1oY94tv38ygLL4o2Hmmu2f/8lDqxGgKV0+KU
    LB/3RWWtGSmNAAvWDvoxLH4udmNe65j+warCala3SjHchn3Wx+x7Gfntys8p1JYvnKK38yk0JtZr
    1NxRJAZAc2PVKF2Wv2JyImIw/SyIAxJ0/YWEEi4oequ7uk4JrmlFGOXAi0W/h2ThCAf1brC/39Lw
    gCXYJlWPAUlg/+KfEnBMREZXe0KRt/mlnmP+zrKKAHrxSp7L3ly3jYoA9J/AVmLKbvyAcMz4YX7O
    UduhP8lIrvotFoak523rSJCEsIPLs4j2xlOGIN8c83wr0X2KOmfD7oZb57s5pV2hWKwhwbgJoo5O
    7LHbijYb57IUBn6guDsu6/5rWoQsBZGlXxOnfi15DE8j9V3Ygile2uGViG5FQwrZlNIqT0YQRFzS
    fLE3/1ieWnpdPqqCCtt/IoNvl6fgIVAzsHoQEaF/cG0InKro7rmGjkGAXw7EvPi8Tfe2t0cmTT4M
    IQGH+8Af7caBQ3NwffmXkqflcPh2yTCCB6QGCSqGSIb3DQEHAaCCB5UEggeRMIIHjTCCB4kGCyqG
    SIb3DQEMCgECoIIHLjCCByowHAYKKoZIhvcNAQwBAzAOBAiuWRHo9x5+rQICCAAEggcI5gmQ6Zed
    e/eyqzLw0PP/clVkiOf9pY6u94DSDs8OUKpqim+GRZlnD0obXem1DNE7lgObOnT9ZCPNwl9Lkr9j
    2mHJll2N4T8fHxFY7V86pZcwr+yZ8ADXYOxSDZyCAZvoSXxCpoJuJJlxy/0H/ieKomyCCvYZ3Le/
    3p3cPTdykgloRRWQpLbvktVEguK61I/8ivP9eLBVlE7U5UyVDs5kipNtuoU2rEvr4E9Tb7LJkfJB
    2hVoe2h7c2YPuOIO/3Q4QQ4Sv6BU1mHUpVvJaHNjiYnQQFeLIEWBAKoLA8P7/QM1PwLAGmNSm3q5
    Wko3kNCDJeOGCO4r6Ak/+RwGWJSzoqTmpBxggD8jiMKWcp1e+9toWaFZcqGpLLWQ/f4NsP4uUlL3
    z8nBKQspYujx7JjhCCuDl0mEd6ZTYdPIb0Z9ukBOBqKYND6MROdj4upziASTlkY5RBZsSwQuRbpw
    jN10/fCloIPeRCyEJrviK+rytOXVm+L6PDz4EBUkgb0DvHyrLdYMJ/P/jiG7sqeIRgU4uqJ7XyeE
    87+Zz2QFMz2WLKEcVpW5fpobOyhPyslzXED5MXFom80b1rBY3EnzSqsm97tfA08WqSC3DvtyuhLU
    jc7ARXcF50/NHmZH9aMCZCgMcvMfRW+MmPm5ou9aLnPy8Q87W/d2IMamtIBnJO087rfLtJ1sWTqu
    JX14wHoLF/1opQXx+lcwjCq3MomcYSZ9IDq2o3itLeeXwu5lC2+RAJqMqqrFPXGDUgZ1RJqzj8FR
    +W57uB0RMXOxGc7XmIPh40lvDF3HeTwKr8CUznUwawzQJbFAD0Z1PWySjnPfv8PcAtzj8Cl7VE0b
    ryxTWbat2q9tRPorQXZb2lCrTgf3KB1Umec0BloWNxrfe9yaiQvEXhnBIJcbpN4UYZl1E7Dnw1Oh
    XHfDZOSzclwgF56avbF3V2OhPWDigrh9XK6j7PLr89EKeO9+zu9hQJC+rHFBQr2EolQpT2yqdg9+
    5jafxTgEu3NzRzH+dVduF7yiCC0MRvbfrKotl2SCCObdln7a76nb+5i6GAzWm5TSxYJoJeMvZ9Mp
    q4J4z9yYED0/Eqzb6fu264R09uUGj4fSWC+ifB2F2px/HIGSRqP7/iw8itd4mO/5nJ6Hvsz3QPcD
    d1oMQraIwT8s2d6MAQbZqK8yA0ci4hQkl71uhB2lQLbcNutllH+n/r97xTNneqAdUsIf1ugSUYEg
    ITVJNPSgcsL1LsS+4YdDOKW6GsGtmxR3NxveBbO3YCJk1MkpJq+p/C7X70F53iv+IrLDjSXce3IB
    jYDFu3PJdNv9hRjKESMA39z9Y5UXDCAL6Tp0lf9gOS7tFGC34QRAZJXMHpoy4Os+k3HWsMI1CH5s
    rmYiIpB3Rgz0Y3HC+98tX1QtkcohNznc8q1W59jLm3oLawhBNQuOKtGQjQSglleaFpBZgOLM2pAl
    nrv19xFg/HSWN5qH85e7LB+atvGnCRpsCe8FfIItHt9Yc2OSSheBkLssULp88d0HJ/DqdsdZIpoo
    chogzzW7xj0k2Y0y8o/uSBs3U98/+JmAGxZvqGEQMsH34lu0pl1RqyOBbMd6YNl+A7evrZ+K+Pnl
    c9Wp8OwAULQkauJmxDh6QWiFbYjhdkgrYNiwDihP+IiiWmON/2IGxwObe++5he8+BhxrQR/JpzYT
    F3HIgHCxvE8xNKiWTqelbym/FirZBuQx6aMhDKYA3XrozdNwCDXwS8jRfpuJe6XocikcINXcX9u0
    2zAZVQAkuMxcrqdNhp8kh0nHYyuX+d3GDoLT29lfSlj+zqRfHteNwmKbtoSyFiym5BsILfktIPd3
    UAMqvCqHd8+VsKmWtxuiMNbym/fhUlFhZk86q1IZ0k8M9Id66DyLUWgHOvHrP6TBu7/6YlnpX/52
    DQ/e1fKZaNdtZkPF9c6prWdfQGlNeyDRje2LBEF1EKHdOOEKpNFPyGXFED+bVrYowdpLBUsqa0k/
    fA8jLaxEEUeAiRGsSae/20mdomNv42vEvGR2Gz1Cr9XurZr317vnrbTQ27OKnT3JBySUpcD5RawE
    tCoVnVY2kX+C37bvMkIyrvfVaGp+s03GayL5gcr0YE7kKQC4zwYh/VsfhrJoLIPtdCuJH5JXPcqh
    pKG0Ob+QChBk+kf5HRNTtqalsl8DnEKJJDk/nXTnifwjttHhApQgzUx2AhxeNzWMijQikLsx24qC
    RU88v1CEA4EkoHdHt1S29SuKeTFK+kJ2EkRI1+0taYK+9WZDGltC03uptltmFh82xQigslYi+E0G
    uC+vIiogqDzSn0ptw68oy1dERNhQV4fuCosHh1J/vT4HBKnLvl6r/2naqCjpnsPe45eRkunjJVND
    c/SRuygfjhKDBNDHuXRxgm/740vMc7FbKNGbMUgwIQYJKoZIhvcNAQkUMRQeEgBLAGEAZgBrAGEA
    VQBzAGUAcjAjBgkqhkiG9w0BCRUxFgQUWPLnkuSCgoDyrGoqXsm67awrZggwMTAhMAkGBSsOAwIa
    BQAEFL3h4LDY0cIdfq17ctygwVO44XigBAh8eYzBYYpkTAICCAA=
  truststore.jks: |
    /u3+7QAAAAIAAAABAAAAAgAHa2Fma2FjYQAAAYBMSsnyAAVYLjUwOQAABDQwggQwMIICmKADAgEC
    AgNBNGkwDQYJKoZIhvcNAQEMBQAwOjE4MDYGA1UEAwwvZDg1NTM1NGQtNjkyOS00Mjk4LWE2YTAt
    ODgxYzBiMjk0M2NjIFByb2plY3QgQ0EwHhcNMTkwODI3MTUyNDA3WhcNMjkwODI0MTUyNDA3WjA6
    MTgwNgYDVQQDDC9kODU1MzU0ZC02OTI5LTQyOTgtYTZhMC04ODFjMGIyOTQzY2MgUHJvamVjdCBD
    QTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALyHC7W8T7hNCb4BVYT+c5aHfe8uAlI4
    L8hZnbjQBVXem8UlHvCmQ4/UQL7s+pWTHZB+mARAl2chxJFGbsYNVyEXq1lgIlhoS3QcMt+MxuUV
    jSn99vCVNXS74Iqbtsc9r6Mu4y+P1dFebTEwJ2pdftb1wN22g+mNzuTLDmLv6wUpwTU0CmNbqaZC
    eOP5MC7mmDspue0KaserHNf9G5v0D+Tz20HS8D7DzrB1hDXNT7+jog9UChQ8opMNAf5N1Upg5BZ4
    TmVSUpTp8mlIuPEjEIpq0PzK8+wH4MeEfK9Udh8c9AYEhcX2r2cy2ZOYh5H+YiR+cb+YAtCZ2DRf
    ecbKKDQY6WTZXL8NNaLN+SaZ8HJZRpCg29VCc8LYZt3FMKnio/j2vrctTrLUoT/sPaeLeKnZSGC1
    nUcHSmYBcMlHcO3Pt+692ynG+fOCFPS5ga+vRuFJFOIwY5pzyqjrEKilMt8jzabulR5Gy8utttqy
    adhfo3+X1n2N5Zr+1ltPeb0umQIDAQABoz8wPTAdBgNVHQ4EFgQULoPG5jF4tqNZkJRden+IREvx
    RBYwDwYDVR0TBAgwBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAAQ0HlAD
    km7Zlu1EJ9M6tUIpQbQNL7Xdcn0JdKBFBXJrEQXHFevwuwCcNSzgQ7FzcTuq49fjWdawIJnAvtl4
    17thszVo6qbR0LDPBWGSi//8HLcCQhapejwSTtLlXf2f9ZnUUm6DQsv4yHVRz3J64zTleCBncKMz
    oGmSUCALPTlSHvztUuj4102hanjYSnja+1dG/EtpCkKhZb+9G3puiP3lsQdTgNx4ZksIOo/eEI79
    nTV56LOAEQikd5t4mg7aS91Q2rVuW5UWeYRqJkyP+u4WCkZrP19T0zBvz7M9X4Ne1uz9gTokyNMX
    c0dsqVUrYjmDEmk0lfhtlqHmrl1n3Psp/Ur+DEczaWlyystW8hnTv9c5j8bNALqpJ5VKqHrsUs4e
    gU+U2KvrnIsSE/1iH1DPpPYUuB53kmtzm1W3OK7FjAj0lw+SR25aRp6S/271hbCYUrSjTPB7Vdyn
    pVUONnVJnPrj3m1WXlA5+UCZyNG6VjbwrdwgOmXUJ9nkyT/8t2opM3wYkadLZG0D3Gfe622Gnskd
stringData:
  KAFKA_SSL_KEYSTORE_PASSWORD: "azerty"
  KAFKA_SSL_TRUSTSTORE_PASSWORD: "azerty"